### ISSUE TITLE
Deserialization support

### ISSUE THREAD

**Issue by chris-olszewski** [robertohuertasm/yarn-lock-parser#12]
Hello, I'm in need of getting being able to pragmatically parse/edit/write `yarn.lock` files both for yarn 1 and 2+. The current parser looks like it is only taking common fields between the two formats in order to provide a unified interface across the two lockfile versions.

Would PRs that make roundtrips possible be appreciated/considered for this project?

**Comment by robertohuertasm** [comment]
HI @chris-olszewski! Not sure if I understood "roundtrips" meaning (non-native speaker, sorry), but in any case, if what you're asking is adding the ability to have more properties in the entries to cover all the possibilities, that could work. Or, expressed in another way, as long as the current API is not broken, I think it should be fine. I created this crate because I needed to have this kind of abstraction between `yarn. lock` versions but I don't see why not to incorporate new functionality.

**Comment by robertohuertasm** [comment]
By the way, thanks for your proposal! 🙌🏻 ❤️

**Comment by chris-olszewski** [comment]
> Not sure if I understood "roundtrips" meaning

Ah sorry, I want to add a new `to_string` function where `lockfile_str == yarn_lock_parser::to_string(yarn_lock_parser::parse_str(lockfile_str)?)`. 

I'll put together a quick PR for that adds this support for yarn 1. Thanks for responding!

**Comment by robertohuertasm** [comment]
Closing as not planned
